import React,{useEffect,useMemo,useState}from'react';
import{Wallet,PiggyBank,Fuel,Utensils,RotateCcw,Save,Banknote,Moon,Sun,TrendingUp,Coins,History,Trash2,FolderOpen,CalendarDays,Plus,Home,ShoppingCart,Receipt,HeartPulse,Plane,GraduationCap,Gift,Car,Gamepad2,Shirt,Coffee,Smartphone,Wrench,MoreHorizontal,ArrowUp,ArrowDown}from'lucide-react';
import{PieChart,Pie,Cell,ResponsiveContainer,Tooltip,Legend,BarChart,Bar,XAxis,YAxis,CartesianGrid}from'recharts';
const now=new Date(),uid=()=>`${Date.now()}-${Math.random().toString(36).slice(2,7)}`;
const iconMap={PiggyBank,Fuel,Utensils,Home,ShoppingCart,Receipt,HeartPulse,Plane,GraduationCap,Gift,Car,Gamepad2,Shirt,Coffee,Smartphone,Wrench,MoreHorizontal};
const iconChoices=[['PiggyBank','Savings'],['Fuel','Fuel'],['Utensils','Going out'],['Home','Rent / home'],['ShoppingCart','Groceries'],['Receipt','Bills'],['HeartPulse','Health'],['Plane','Travel'],['GraduationCap','Education'],['Gift','Gifts'],['Car','Car'],['Gamepad2','Entertainment'],['Shirt','Clothes'],['Coffee','Coffee'],['Smartphone','Phone'],['Wrench','Repairs'],['MoreHorizontal','Other']];
const palette=['#22c55e','#f97316','#8b5cf6','#0ea5e9','#ef4444','#eab308','#14b8a6','#ec4899','#6366f1','#84cc16','#f43f5e','#06b6d4'];
const defaultCategories=[{id:'savings',name:'Savings',icon:'PiggyBank',method:'percent',value:20,color:'#22c55e'},{id:'fuel',name:'Fuel',icon:'Fuel',method:'fixed',value:500,color:'#f97316'},{id:'going-out',name:'Going out',icon:'Utensils',method:'percent',value:10,color:'#8b5cf6'}];
const defaults={month:`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}`,regularHours:160,hourlyRate:40,overtimeHours:0,overtimeMultiplier:1.25,bonus:0,otherAdditions:0,deductions:0,currency:'ILS',categories:defaultCategories};
const currencies=[{code:'ILS',label:'Israeli Shekel',symbol:'₪',locale:'he-IL'},{code:'USD',label:'US Dollar',symbol:'$',locale:'en-US'},{code:'EUR',label:'Euro',symbol:'€',locale:'de-DE'},{code:'GBP',label:'British Pound',symbol:'£',locale:'en-GB'}];
function normalize(raw){const f={...defaults,...raw};if(!Array.isArray(f.categories)){f.categories=[{...defaultCategories[0],value:raw?.savingsPercent??20},{...defaultCategories[1],value:raw?.fuelBudget??500},{...defaultCategories[2],value:raw?.goingOutPercent??10}]}return f}
function calculate(f){const regularPay=f.regularHours*f.hourlyRate,overtimePay=f.overtimeHours*f.hourlyRate*f.overtimeMultiplier,gross=regularPay+overtimePay+f.bonus+f.otherAdditions,net=gross-f.deductions,usable=Math.max(0,net);let remaining=usable;const allocations=f.categories.map(cat=>{const requested=cat.method==='percent'?usable*(cat.value/100):cat.value,amount=Math.min(remaining,Math.max(0,requested));remaining-=amount;return{...cat,amount}});return{regularPay,overtimePay,gross,net,remaining,allocations}}
function Field({label,value,onChange,suffix,step='.01'}){return <label className="field"><span>{label}</span><div className="inputWrap"><input type="number" inputMode="decimal" min="0" step={step} value={value} onChange={e=>onChange(Math.max(0,Number(e.target.value)||0))}/>{suffix&&<b>{suffix}</b>}</div></label>}
function Icon({name,size=20}){const C=iconMap[name]||MoreHorizontal;return <C size={size}/>}
export default function App(){
 const[form,setForm]=useState(()=>{try{return normalize(JSON.parse(localStorage.getItem('paycheck-current')||'{}'))}catch{return defaults}}),[history,setHistory]=useState(()=>{try{return JSON.parse(localStorage.getItem('paycheck-history')||'[]')}catch{return[]}}),[dark,setDark]=useState(()=>localStorage.getItem('paycheck-theme')==='dark'),[saved,setSaved]=useState(false);
 const currency=currencies.find(x=>x.code===form.currency)||currencies[0],money=v=>new Intl.NumberFormat(currency.locale,{style:'currency',currency:currency.code,maximumFractionDigits:0}).format(Number.isFinite(v)?v:0),set=(k,v)=>setForm(x=>({...x,[k]:v})),c=useMemo(()=>calculate(form),[form]);
 useEffect(()=>{document.documentElement.dataset.theme=dark?'dark':'light';localStorage.setItem('paycheck-theme',dark?'dark':'light')},[dark]);useEffect(()=>localStorage.setItem('paycheck-current',JSON.stringify(form)),[form]);
 const updateCat=(id,key,value)=>setForm(f=>({...f,categories:f.categories.map(x=>x.id===id?{...x,[key]:value}:x)})),addCat=()=>setForm(f=>({...f,categories:[...f.categories,{id:uid(),name:'New category',icon:'MoreHorizontal',method:'fixed',value:0,color:palette[f.categories.length%palette.length]}]})),removeCat=id=>setForm(f=>({...f,categories:f.categories.filter(x=>x.id!==id)})),moveCat=(i,d)=>setForm(f=>{const a=[...f.categories],j=i+d;if(j<0||j>=a.length)return f;[a[i],a[j]]=[a[j],a[i]];return{...f,categories:a}});
 const saveMonth=()=>{const record={...form,...c,id:form.month,savedAt:new Date().toISOString()};setHistory(old=>{const next=[...old.filter(x=>x.id!==record.id),record].sort((a,b)=>b.id.localeCompare(a.id));localStorage.setItem('paycheck-history',JSON.stringify(next));return next});setSaved(true);setTimeout(()=>setSaved(false),1400)},loadMonth=r=>{setForm(normalize(r));window.scrollTo({top:0,behavior:'smooth'})},deleteMonth=id=>setHistory(old=>{const next=old.filter(x=>x.id!==id);localStorage.setItem('paycheck-history',JSON.stringify(next));return next}),reset=()=>setForm({...defaults,month:form.month,currency:form.currency,categories:defaultCategories.map(x=>({...x}))});
 const pie=[...c.allocations.map(x=>({name:x.name,value:x.amount,color:x.color})),{name:'Remaining',value:c.remaining,color:'#0ea5e9'}].filter(x=>x.value>0),year=form.month.slice(0,4),yearRows=[...history].filter(x=>x.month?.startsWith(year)).sort((a,b)=>a.month.localeCompare(b.month)),yearAllocated=yearRows.reduce((s,r)=>s+(r.allocations||[]).reduce((a,x)=>a+(x.amount||0),0),0),yearNet=yearRows.reduce((s,r)=>s+(r.net||0),0);
 return <main><div className="shell"><header><div className="badge"><Wallet size={16}/> MY PAYCHECK PLAN</div><button className="theme" onClick={()=>setDark(x=>!x)}>{dark?<Sun/>:<Moon/>}</button><h1>Give every part of your pay a purpose</h1><p>Create your own spending and saving categories, choose their icons, and save a separate plan for every month.</p></header>
 <section className="layout"><article className="card"><Title icon="Banknote" title="1. What did I earn?" text="Enter this month’s work, additions, and deductions."/><div className="grid"><label className="field"><span>Month</span><input type="month" value={form.month} onChange={e=>set('month',e.target.value)}/></label><label className="field"><span>Currency</span><div className="selectWrap"><Coins size={17}/><select value={form.currency} onChange={e=>set('currency',e.target.value)}>{currencies.map(x=><option key={x.code} value={x.code}>{x.symbol} {x.code} · {x.label}</option>)}</select></div></label><Field label="Regular hours" value={form.regularHours} onChange={v=>set('regularHours',v)}/><Field label="Hourly rate" value={form.hourlyRate} onChange={v=>set('hourlyRate',v)} suffix={currency.symbol}/><Field label="Overtime hours" value={form.overtimeHours} onChange={v=>set('overtimeHours',v)}/><Field label="Overtime multiplier" value={form.overtimeMultiplier} onChange={v=>set('overtimeMultiplier',v)} suffix="×" step=".05"/><Field label="Bonus" value={form.bonus} onChange={v=>set('bonus',v)} suffix={currency.symbol}/><Field label="Other additions" value={form.otherAdditions} onChange={v=>set('otherAdditions',v)} suffix={currency.symbol}/><div className="wide"><Field label="Taxes and deductions" value={form.deductions} onChange={v=>set('deductions',v)} suffix={currency.symbol}/></div></div><div className="summary"><Sum label="Regular pay" value={c.regularPay} money={money}/><Sum label="Overtime" value={c.overtimePay} money={money}/><Sum label="Gross pay" value={c.gross} money={money}/><Sum label="Net pay" value={c.net} money={money} strong/></div></article>
 <div className="stack"><article className="card categories"><Title icon="PiggyBank" title="2. Where should it go?" text="Add as many categories as you need. Categories are funded from top to bottom."/>{form.categories.map((cat,i)=><div className="category" key={cat.id} style={{'--cat':cat.color}}><div className="catTop"><span className="catIcon"><Icon name={cat.icon}/></span><input className="catName" value={cat.name} onChange={e=>updateCat(cat.id,'name',e.target.value)}/><div className="order"><button onClick={()=>moveCat(i,-1)} disabled={i===0}><ArrowUp/></button><button onClick={()=>moveCat(i,1)} disabled={i===form.categories.length-1}><ArrowDown/></button><button className="remove" onClick={()=>removeCat(cat.id)}><Trash2/></button></div></div><div className="catControls"><label><span>Icon</span><select value={cat.icon} onChange={e=>updateCat(cat.id,'icon',e.target.value)}>{iconChoices.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label><span>Type</span><select value={cat.method} onChange={e=>updateCat(cat.id,'method',e.target.value)}><option value="fixed">Fixed amount</option><option value="percent">Percentage</option></select></label><label><span>{cat.method==='percent'?'Percent':'Amount'}</span><div className="miniInput"><input type="number" min="0" value={cat.value} onChange={e=>updateCat(cat.id,'value',Math.max(0,Number(e.target.value)||0))}/><b>{cat.method==='percent'?'%':currency.symbol}</b></div></label></div><div className="allocated">Allocated <b>{money(c.allocations.find(x=>x.id===cat.id)?.amount||0)}</b></div></div>)}<button className="addCat" onClick={addCat}><Plus/> Add another category</button></article>
 <div className="metrics">{c.allocations.map(x=><Metric key={x.id} cat={x} money={money}/>)}<Metric cat={{name:'Remaining',icon:'Banknote',amount:c.remaining,color:'#0ea5e9'}} money={money}/></div><article className="card chart"><h2>Current month allocation</h2><ResponsiveContainer width="100%" height={285}><PieChart><Pie data={pie} dataKey="value" nameKey="name" innerRadius={55} outerRadius={88}>{pie.map((x,i)=><Cell key={i} fill={x.color}/>)}</Pie><Tooltip formatter={v=>money(Number(v))}/><Legend/></PieChart></ResponsiveContainer></article></div></section>
 <article className="card history"><div className="historyHead"><div><h2><History/> Monthly history</h2><p>Each saved month keeps its own categories and icons.</p></div><span>{history.length} saved</span></div>{history.length===0?<Empty/>:<div className="historyList">{history.map(r=><div className="historyRow" key={r.id}><button className="loadRow" onClick={()=>loadMonth(r)}><b>{new Date(r.month+'-02').toLocaleDateString(undefined,{month:'long',year:'numeric'})}</b><span>Net {money(r.net)} · {r.allocations?.length||r.categories?.length||0} categories</span></button><button className="openBtn" onClick={()=>loadMonth(r)}><FolderOpen/></button><button className="deleteBtn" onClick={()=>deleteMonth(r.id)}><Trash2/></button></div>)}</div>}</article>
 <article className="card annual"><div className="annualHead"><div><h2><TrendingUp/> {year} saved-month overview</h2><p>Compares net pay with everything assigned to your categories.</p></div><div><small>Total allocated</small><strong>{money(yearAllocated)}</strong><small>Net income {money(yearNet)}</small></div></div>{yearRows.length?<ResponsiveContainer width="100%" height={300}><BarChart data={yearRows.map(x=>({month:new Date(x.month+'-02').toLocaleDateString(undefined,{month:'short'}),allocated:(x.allocations||[]).reduce((s,a)=>s+(a.amount||0),0),net:x.net}))}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="month"/><YAxis tickFormatter={v=>Intl.NumberFormat(currency.locale,{notation:'compact'}).format(v)}/><Tooltip formatter={v=>money(Number(v))}/><Legend/><Bar dataKey="allocated" name="Allocated" fill="#22c55e" radius={[6,6,0,0]}/><Bar dataKey="net" name="Net pay" fill="#3b82f6" radius={[6,6,0,0]}/></BarChart></ResponsiveContainer>:<div className="empty">Save a month in {year} to show the chart.</div>}</article></div><nav><button className="secondary" onClick={reset}><RotateCcw/>Reset categories</button><button className="primary" onClick={saveMonth}><Save/>{saved?'Month saved':'Save this month'}</button></nav></main>}
function Title({icon,title,text}){const C=icon==='Banknote'?Banknote:PiggyBank;return <div className="title"><i><C/></i><h2>{title}</h2><p>{text}</p></div>}function Sum({label,value,money,strong}){return <div><small>{label}</small><b className={strong?'accent':''}>{money(value)}</b></div>}function Metric({cat,money}){return <div className="metric"><i style={{background:`${cat.color}22`,color:cat.color}}><Icon name={cat.icon}/></i><div><small>{cat.name}</small><strong>{money(cat.amount)}</strong></div></div>}function Empty(){return <div className="empty"><CalendarDays/><b>No saved months yet</b><p>Build your categories and tap Save this month.</p></div>}
